package sap_api_input_reader

import (
	"sap-api-integrations-maintenance-notification-creates/SAP_API_Caller/requests"
)

func (sdc *SDC) ConvertToHeader() *requests.Header {
	data := sdc.MaintenanceNotification
	return &requests.Header{
	MaintenanceNotification:        data.MaintenanceNotification,
	MaintNotifInternalID:           data.MaintNotifInternalID,
	NotificationText:               data.NotificationText,
	MaintPriority:                  data.MaintPriority,
	NotificationType:               data.NotificationType,
	NotifProcessingPhase:           data.NotifProcessingPhase,
	NotifProcessingPhaseDesc:       data.NotifProcessingPhaseDesc,
	MaintPriorityDesc:              data.MaintPriorityDesc,
	CreationDate:                   data.CreationDate,
	LastChangeTime:                 data.LastChangeTime,
	LastChangeDate:                 data.LastChangeDate,
	LastChangeDateTime:             data.LastChangeDateTime,
	CreationTime:                   data.CreationTime,
	ReportedByUser:                 data.ReportedByUser,
	ReporterFullName:               data.ReporterFullName,
	PersonResponsible:              data.PersonResponsible,
	MalfunctionEffect:              data.MalfunctionEffect,
	MalfunctionEffectText:          data.MalfunctionEffectText,
	MalfunctionStartDate:           data.MalfunctionStartDate,
	MalfunctionStartTime:           data.MalfunctionStartTime,
	MalfunctionEndDate:             data.MalfunctionEndDate,
	MalfunctionEndTime:             data.MalfunctionEndTime,
	MaintNotificationCatalog:       data.MaintNotificationCatalog,
	MaintNotificationCode:          data.MaintNotificationCode,
	MaintNotificationCodeGroup:     data.MaintNotificationCodeGroup,
	CatalogProfile:                 data.CatalogProfile,
	NotificationCreationDate:       data.NotificationCreationDate,
	NotificationCreationTime:       data.NotificationCreationTime,
	NotificationTimeZone:           data.NotificationTimeZone,
	RequiredStartDate:              data.RequiredStartDate,
	RequiredStartTime:              data.RequiredStartTime,
	RequiredEndDate:                data.RequiredEndDate,
	RequiredEndTime:                data.RequiredEndTime,
	LatestAcceptableCompletionDate: data.LatestAcceptableCompletionDate,
	MaintenanceObjectIsDown:        data.MaintenanceObjectIsDown,
	MaintNotificationLongText:      data.MaintNotificationLongText,
	MaintNotifLongTextForEdit:      data.MaintNotifLongTextForEdit,
	TechnicalObject:                data.TechnicalObject,
	TechObjIsEquipOrFuncnlLoc:      data.TechObjIsEquipOrFuncnlLoc,
	TechnicalObjectLabel:           data.TechnicalObjectLabel,
	MaintenancePlanningPlant:       data.MaintenancePlanningPlant,
	MaintenancePlannerGroup:        data.MaintenancePlannerGroup,
	SuperiorTechnicalObject:        data.SuperiorTechnicalObject,
	SuperiorTechnicalObjectName:    data.SuperiorTechnicalObjectName,
	SuperiorObjIsEquipOrFuncnlLoc:  data.SuperiorObjIsEquipOrFuncnlLoc,
	SuperiorTechnicalObjectLabel:   data.SuperiorTechnicalObjectLabel,
	ManufacturerPartTypeName:       data.ManufacturerPartTypeName,
	TechObjIsEquipOrFuncnlLocDesc:  data.TechObjIsEquipOrFuncnlLocDesc,
	FunctionalLocation:             data.FunctionalLocation,
	FunctionalLocationLabelName:    data.FunctionalLocationLabelName,
	TechnicalObjectDescription:     data.TechnicalObjectDescription,
	AssetLocation:                  data.AssetLocation,
	LocationName:                   data.LocationName,
	BusinessArea:                   data.BusinessArea,
	CompanyCode:                    data.CompanyCode,
	TechnicalObjectCategory:        data.TechnicalObjectCategory,
	TechnicalObjectType:            data.TechnicalObjectType,
	MainWorkCenterPlant:            data.MainWorkCenterPlant,
	MainWorkCenter:                 data.MainWorkCenter,
	PlantName:                      data.PlantName,
	MaintenancePlannerGroupName:    data.MaintenancePlannerGroupName,
	MaintenancePlant:               data.MaintenancePlant,
	LocationDescription:            data.LocationDescription,
	MainWorkCenterText:             data.MainWorkCenterText,
	MainWorkCenterPlantName:        data.MainWorkCenterPlantName,
	MaintenancePlantName:           data.MaintenancePlantName,
	PlantSectionPersonRespName:     data.PlantSectionPersonRespName,
	PersonResponsibleName:          data.PersonResponsibleName,
	MaintenanceOrder:               data.MaintenanceOrder,
	MaintenanceOrderType:           data.MaintenanceOrderType,
	MaintenanceActivityType:        data.MaintenanceActivityType,
	MaintObjDowntimeDurationUnit:   data.MaintObjDowntimeDurationUnit,
	MaintObjectDowntimeDuration:    data.MaintObjectDowntimeDuration,
	MaintenancePlan:                data.MaintenancePlan,
	MaintenanceItem:                data.MaintenanceItem,
	TaskListGroup:                  data.TaskListGroup,
	TaskListGroupCounter:           data.TaskListGroupCounter,
	MaintenancePlanCallNumber:      data.MaintenancePlanCallNumber,
	MaintenanceTaskListType:        data.MaintenanceTaskListType,
	NotificationReferenceDate:      data.NotificationReferenceDate,
	NotificationReferenceTime:      data.NotificationReferenceTime,
	NotificationCompletionDate:     data.NotificationCompletionDate,
	CompletionTime:                 data.CompletionTime,
	AssetRoom:                      data.AssetRoom,
	MaintNotifExtReferenceNumber:   data.MaintNotifExtReferenceNumber,
	MaintNotifRejectionReasonCode:  data.MaintNotifRejectionReasonCode,
	MaintNotifRejectionRsnCodeTxt:  data.MaintNotifRejectionRsnCodeTxt,
	MaintNotifDetectionCatalog:     data.MaintNotifDetectionCatalog,
	MaintNotifDetectionCode:        data.MaintNotifDetectionCode,
	MaintNotifDetectionCodeText:    data.MaintNotifDetectionCodeText,
	MaintNotifDetectionCodeGroup:   data.MaintNotifDetectionCodeGroup,
	MaintNotifDetectionCodeGrpTxt:  data.MaintNotifDetectionCodeGrpTxt,
	MaintNotifProcessPhaseCode:     data.MaintNotifProcessPhaseCode,
	MaintNotifProcessSubPhaseCode:  data.MaintNotifProcessSubPhaseCode,
	ToItem: &struct {
			ToItemResults []*requests.Item `json:"results"`
		}{
			ToItemResults: []*requests.Item{
				sdc.ConvertToItem(),
			},
		},
	}
}

func (sdc *SDC) ConvertToItem() *requests.Item {
	dataHeader := sdc.MaintenanceNotification
	data := sdc.MaintenanceNotification.MaintenanceNotificationItem
	return &requests.Item{
	MaintenanceNotification:       dataHeader.MaintenanceNotification,
	MaintenanceNotificationItem:   data.MaintenanceNotificationItem,
	MaintNotifItemText:            data.MaintNotifItemText,
	MaintNotifDamageCodeGroup:     data.MaintNotifDamageCodeGroup,
	MaintNotifDamageCodeGroupName: data.MaintNotifDamageCodeGroupName,
	MaintNotificationDamageCode:   data.MaintNotificationDamageCode,
	MaintNotifDamageCodeName:      data.MaintNotifDamageCodeName,
	MaintNotifObjPrtCodeGroup:     data.MaintNotifObjPrtCodeGroup,
	MaintNotifObjPrtCodeGroupName: data.MaintNotifObjPrtCodeGroupName,
	MaintNotifObjPrtCode:          data.MaintNotifObjPrtCode,
	MaintNotifObjPrtCodeName:      data.MaintNotifObjPrtCodeName,
	IsDeleted:                     data.IsDeleted,
	}
}
